import json
import os

# 299 Master Records as supplied by the user
records = [
  {"nca": 1, "title": "No Wee Wi Mutheru", "old": 1, "nzk": 1, "nzk_t": "Mtakatifu, Mtakatifu, Mtakatifu", "sdah": 73, "sdah_t": "Holy, Holy, Holy", "tune": "Nicaea", "cat": "Worship & Adoration"},
  {"nca": 2, "title": "Twakugatha Ngai", "old": 2, "nzk": 2, "nzk_t": "Twamsifu Mungu", "sdah": 334, "sdah_t": "Revive Us Again", "tune": "Revive Us Again", "cat": "Praise & Thanksgiving"},
  {"nca": 3, "title": "Ngai Niagoocwo Nĩ Ciumbe Ciake", "old": 3, "nzk": 3, "nzk_t": "Mungu Atukuzwe", "sdah": 341, "sdah_t": "To God Be the Glory", "tune": "To God Be the Glory", "cat": "Praise & Thanksgiving"},
  {"nca": 4, "title": "Kumiai Riitwa Ria Jesu", "old": 4, "nzk": 4, "nzk_t": "Jina La Yesu, Salamu", "sdah": 229, "sdah_t": "All Hail the Power of Jesus' Name", "tune": "Coronation", "cat": "Worship & Adoration"},
  {"nca": 5, "title": "Nitumuhooe Jesu Munene", "old": 5, "nzk": 5, "nzk_t": "Na Tumwabudu Mfalme Mtukufu", "sdah": 83, "sdah_t": "O Worship the King", "tune": "Lyons", "cat": "Worship & Adoration"},
  {"nca": 6, "title": "Ruciini Gukiire Wega", "old": 6, "nzk": 6, "nzk_t": "Kumekucha Kwa Uzuri", "sdah": 39, "sdah_t": "Lord, in the Morning", "tune": "Warwick", "cat": "Morning & Evening Worship"},
  {"nca": 7, "title": "Ngai Atuire Atuteithagia", "old": 7, "nzk": 7, "nzk_t": "Mungu Msaada Wetu", "sdah": 103, "sdah_t": "O God, Our Help in Ages Past", "tune": "St. Anne", "cat": "Worship & Adoration"},
  {"nca": 8, "title": "Njigua Ngikaya", "old": 8, "nzk": 8, "nzk_t": "Uje Mkombozi", "sdah": 338, "sdah_t": "Come, Thou Long-Expected Jesus", "tune": "Hyfrydol", "cat": "Gospel Invitation & Repentance"},
  {"nca": 9, "title": "Muthamaki Muumbi", "old": 9, "nzk": 9, "nzk_t": "Mwumbaji, Mfalme", "sdah": 15, "sdah_t": "My Maker and My King", "tune": "Short Meter", "cat": "Worship & Adoration"},
  {"nca": 10, "title": "Kristo Muiguaniri Tha", "old": 10, "nzk": 10, "nzk_t": "Kristo Wa Neema Yote", "sdah": 334, "sdah_t": "Come, Thou Fount of Every Blessing", "tune": "Nettleton", "cat": "Praise & Thanksgiving"},
  {"nca": 11, "title": "Jesu Uugite Eri Kana Atatu", "old": 11, "nzk": 13, "nzk_t": "Umetuahidi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 12, "title": "Migambo Yothe Nĩ iinire", "old": 12, "nzk": 11, "nzk_t": "Sauti Zote Ziimbe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 13, "title": "Gathai Ngai Andu Aya", "old": 13, "nzk": 12, "nzk_t": "Msifu Mungu", "sdah": 694, "sdah_t": "Praise God, From Whom All Blessings Flow", "tune": "Old 100th", "cat": "Benedictions & Doxologies"},
  {"nca": 14, "title": "Reke Njerage Nawe Ngai", "old": 14, "nzk": 14, "nzk_t": "Nitembee Nawe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 15, "title": "Njariria Mwathani Jesu", "old": 15, "nzk": 15, "nzk_t": "Nena Rohoni Yesu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 16, "title": "Jesu Nimbatairio Niwe", "old": 16, "nzk": 16, "nzk_t": "Bwana Ninakuhitaji", "sdah": 483, "sdah_t": "I Need Thee Every Hour", "tune": "Need", "cat": "Prayer & Christian Fellowship"},
  {"nca": 17, "title": "Ti Nii No Kristo", "old": 17, "nzk": 17, "nzk_t": "Si Mimi, Kristo", "sdah": 570, "sdah_t": "Not I, but Christ", "tune": "Not I, but Christ", "cat": "Consecration, Trust & Living"},
  {"nca": 18, "title": "Tutongorie O Ta Muriithi", "old": 18, "nzk": 18, "nzk_t": "Mwokozi, Kama Mchunga", "sdah": 545, "sdah_t": "Savior, Like a Shepherd Lead Us", "tune": "Bradbury", "cat": "Consecration, Trust & Living"},
  {"nca": 19, "title": "Mutharaba-ini wa Mwathani", "old": 19, "nzk": 19, "nzk_t": "Msalabani Pa Mwokozi", "sdah": 309, "sdah_t": "Glory to His Name / Down at the Cross", "tune": "Down at the Cross", "cat": "Salvation, Atonement & Grace"},
  {"nca": 20, "title": "Ngai Witu Ni Ta Ruaro", "old": 20, "nzk": 20, "nzk_t": "Mungu Wetu Yeye Mwamba", "sdah": 506, "sdah_t": "A Mighty Fortress Is Our God", "tune": "Ein Feste Burg", "cat": "Salvation, Atonement & Grace"},
  {"nca": 21, "title": "Ukaani Tukumie Jesu", "old": 21, "nzk": 21, "nzk_t": "Baba Twakujia", "sdah": 484, "sdah_t": "I Need Thee, Precious Jesus", "tune": "Father, We Come", "cat": "Prayer & Christian Fellowship"},
  {"nca": 22, "title": "Ndukandige Muhonokia", "old": 22, "nzk": 22, "nzk_t": "Usinipite, Mwokozi", "sdah": 569, "sdah_t": "Pass Me Not, O Gentle Savior", "tune": "Pass Me Not", "cat": "Prayer & Christian Fellowship"},
  {"nca": 23, "title": "Ningwendete Jesu", "old": 23, "nzk": 29, "nzk_t": "Yesu Nakupenda", "sdah": 321, "sdah_t": "My Jesus, I Love Thee", "tune": "Gordon", "cat": "Consecration, Trust & Living"},
  {"nca": 24, "title": "Jesu Mukuuri Wakwa", "old": 24, "nzk": 31, "nzk_t": "Niimbe Pendo Lake", "sdah": 152, "sdah_t": "Tell Me the Story of Jesus", "tune": "Jesus My Savior", "cat": "Salvation, Atonement & Grace"},
  {"nca": 25, "title": "Jesu Gikeno Kia Ngoro", "old": 25, "nzk": 23, "nzk_t": "Yesu Furaha Ya Moyo", "sdah": 242, "sdah_t": "Jesus, the Very Thought of Thee", "tune": "St. Agnes", "cat": "Consecration, Trust & Living"},
  {"nca": 26, "title": "Niekiruo Thuumbi", "old": 26, "nzk": 25, "nzk_t": "Taji Mvikeni", "sdah": 223, "sdah_t": "Crown Him With Many Crowns", "tune": "Diademata", "cat": "Salvation, Atonement & Grace"},
  {"nca": 27, "title": "Ni Ka Na Ku Gakeenge?", "old": 27, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 28, "title": "Ninagainaga Uhoro Mwega", "old": 28, "nzk": 11, "nzk_t": "Sauti Zote Ziimbe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 29, "title": "Ukaani Andu Aria", "old": 29, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 30, "title": "Riitwa Ria Jesu Ni Riega", "old": 30, "nzk": 24, "nzk_t": "Jina Lake Yesu Tamu", "sdah": 232, "sdah_t": "How Sweet the Name of Jesus Sounds", "tune": "St. Peter", "cat": "Praise & Thanksgiving"},
  {"nca": 31, "title": "Jesu Muukuri Ruaro Rurumu", "old": 31, "nzk": 40, "nzk_t": "Jesu Muukuri Ruaro Rurumu", "sdah": 507, "sdah_t": "A Shelter in the Time of Storm", "tune": "A Shelter in the Time of Storm", "cat": "Salvation, Atonement & Grace"},
  {"nca": 32, "title": "Mbuku Ya Ngai", "old": 32, "nzk": 52, "nzk_t": "Mbuku Ya Ngai", "sdah": 272, "sdah_t": "Give Me the Bible", "tune": "Give Me the Bible", "cat": "Holy Scriptures & Word of God"},
  {"nca": 33, "title": "Turaatime Tugithii", "old": 33, "nzk": 26, "nzk_t": "Tutokapo Tubariki", "sdah": 67, "sdah_t": "Lord, Dismiss Us With Thy Blessing", "tune": "Sicilian Mariners", "cat": "Benedictions & Doxologies"},
  {"nca": 34, "title": "O Ringi Jesu Nitwarikumia", "old": 34, "nzk": 27, "nzk_t": "Tena Mwokozi Twalitukuza", "sdah": 249, "sdah_t": "Praise Him! Praise Him!", "tune": "Joyful Song", "cat": "Praise & Thanksgiving"},
  {"nca": 35, "title": "Oya Riitwa Riu Ria Jesu", "old": 35, "nzk": 28, "nzk_t": "Jina La Thamani", "sdah": 474, "sdah_t": "Take the Name of Jesus with You", "tune": "Precious Name", "cat": "Salvation, Atonement & Grace"},
  {"nca": 36, "title": "Jesu Ningwendetee", "old": 36, "nzk": 29, "nzk_t": "Yesu Nakupenda", "sdah": 321, "sdah_t": "My Jesus, I Love Thee", "tune": "Gordon", "cat": "Salvation, Atonement & Grace"},
  {"nca": 37, "title": "Jesu Niunyendeete", "old": 37, "nzk": 30, "nzk_t": "Yesu Anipenda", "sdah": 190, "sdah_t": "Jesus Loves Me", "tune": "Jesus Loves Me", "cat": "Salvation, Atonement & Grace"},
  {"nca": 38, "title": "Nguinira Wendo Wake", "old": 38, "nzk": 31, "nzk_t": "Niimbe Pendo Lake", "sdah": 340, "sdah_t": "Jesus Saves", "tune": "Jesus Saves", "cat": "Praise & Thanksgiving"},
  {"nca": 39, "title": "Ndi Ruimbo Nyendeete Kuina", "old": 39, "nzk": 32, "nzk_t": "Ninao Wimbo Mzuri", "sdah": 462, "sdah_t": "He Hideth My Soul", "tune": "Kirkpatrick", "cat": "Praise & Thanksgiving"},
  {"nca": 40, "title": "Niakuire Muti-ini", "old": 40, "nzk": 141, "nzk_t": "Chini ya Msalaba", "sdah": 163, "sdah_t": "At the Cross / Alas! and Did My Savior Bleed", "tune": "Hudson", "cat": "Salvation, Atonement & Grace"},
  {"nca": 41, "title": "O Ruciini Nituonaga", "old": 41, "nzk": 90, "nzk_t": "Mapya Ni Mapenzi", "sdah": 39, "sdah_t": "New Every Morning is the Love", "tune": "Melcombe", "cat": "Morning & Evening Worship"},
  {"nca": 42, "title": "Uhoro Wa Muoyo", "old": 42, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 43, "title": "Njira Uhoro Wa Jesu", "old": 43, "nzk": 34, "nzk_t": "Nipe Habari za Yesu", "sdah": 152, "sdah_t": "Tell Me the Story of Jesus", "tune": "Story of Jesus", "cat": "Worship & Adoration"},
  {"nca": 44, "title": "Nindakuuriruo Ni Mwathani", "old": 44, "nzk": 35, "nzk_t": "Nimekombolewa na Yesu", "sdah": 337, "sdah_t": "Redeemed, How I Love to Proclaim It", "tune": "Redeemed", "cat": "Salvation, Atonement & Grace"},
  {"nca": 45, "title": "Ni Muthenya Wa Munyaka", "old": 45, "nzk": 36, "nzk_t": "Ni Siku Kuu", "sdah": 382, "sdah_t": "O Day of Rest and Gladness", "tune": "Mendebras", "cat": "The Sabbath"},
  {"nca": 46, "title": "Ngoro Yakwa No Ihote", "old": 46, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 47, "title": "Riu Turaathime Jesu", "old": 47, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Benedictions & Doxologies"},
  {"nca": 48, "title": "Jehova Wa Kuu Betheli", "old": 48, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 49, "title": "Nguucia Hari We Jesu", "old": 49, "nzk": 33, "nzk_t": "Karibu Sana", "sdah": 301, "sdah_t": "Nearer, Still Nearer", "tune": "Morris", "cat": "Prayer & Christian Fellowship"},
  {"nca": 50, "title": "Jesu Niarihite Thiiri", "old": 50, "nzk": 119, "nzk_t": "Yesu Anasema", "sdah": 281, "sdah_t": "Jesus Paid It All", "tune": "All to Christ", "cat": "Salvation, Atonement & Grace"},
  {"nca": 51, "title": "Ngondu Miroongo Kenda Na Kenda", "old": 51, "nzk": 104, "nzk_t": "Kondoo Mia Moja Walilala", "sdah": 373, "sdah_t": "The Ninety and Nine", "tune": "The Ninety and Nine", "cat": "Salvation, Atonement & Grace"},
  {"nca": 52, "title": "Muhonokia, Ndoongoria", "old": 52, "nzk": 73, "nzk_t": "Mwongozi Ee Yehova", "sdah": 545, "sdah_t": "Guide Me, O Thou Great Jehovah", "tune": "Cwm Rhondda", "cat": "Consecration, Trust & Living"},
  {"nca": 53, "title": "Muumbi Wa Thi O Na Iria", "old": 53, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 54, "title": "Muru Wa Ngai Niokire", "old": 54, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 55, "title": "Ninguinira Ngai Hoti", "old": 55, "nzk": 38, "nzk_t": "Nasifu Shani ya Mungu", "sdah": 88, "sdah_t": "I Sing the Mighty Power of God", "tune": "Varina", "cat": "Praise & Thanksgiving"},
  {"nca": 56, "title": "Mwathani Ninjiguaga", "old": 56, "nzk": 39, "nzk_t": "Ati Kuna Mvua Njema", "sdah": 195, "sdah_t": "Showers of Blessing", "tune": "Showers of Blessing", "cat": "Prayer & Christian Fellowship"},
  {"nca": 57, "title": "Wee Roho Mutheru Uka", "old": 57, "nzk": 40, "nzk_t": "Njoo, Roho Mtukufu", "sdah": 260, "sdah_t": "Hover O'er Me, Holy Spirit", "tune": "Hover O'er Me", "cat": "Worship & Adoration"},
  {"nca": 58, "title": "We Roho Mutheru Ma", "old": 58, "nzk": 41, "nzk_t": "Roho Mtakatifu", "sdah": 261, "sdah_t": "The Spirit of the Lord Revealed", "tune": None, "cat": "Worship & Adoration"},
  {"nca": 59, "title": "Wee Roho Wa Matu-ini", "old": 59, "nzk": 42, "nzk_t": "Ewe Roho wa Mbinguni", "sdah": 268, "sdah_t": "Holy Spirit, Light Divine", "tune": "Mercy", "cat": "Worship & Adoration"},
  {"nca": 60, "title": "Riua Nirithuire", "old": 60, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Morning & Evening Worship"},
  {"nca": 61, "title": "Ndaagia Gikeno Na Ngwataniro", "old": 61, "nzk": 43, "nzk_t": "Furaha Gani", "sdah": 342, "sdah_t": "Is This the Day?", "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 62, "title": "Gutiri Na Muraata Ta Jesu", "old": 62, "nzk": 44, "nzk_t": "Hakuna Rafiki Kama Yesu", "sdah": 499, "sdah_t": "No, Not One!", "tune": "No, Not One", "cat": "Consecration, Trust & Living"},
  {"nca": 63, "title": "Utheri Wi Kirima-ini", "old": 63, "nzk": 45, "nzk_t": "Mlimani Pana Mwanga", "sdah": 580, "sdah_t": "This Little Light of Mine", "tune": None, "cat": "Worship & Adoration"},
  {"nca": 64, "title": "Guikaraga Hari Jesu", "old": 64, "nzk": 46, "nzk_t": "Miguuni Pake Yesu", "sdah": 290, "sdah_t": "Turn Your Eyes Upon Jesus", "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 65, "title": "Mwaathani Ningwendete Ma", "old": 65, "nzk": 48, "nzk_t": "Ninakupenda Zaidi", "sdah": 319, "sdah_t": "Lord, I Want to Be a Christian", "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 66, "title": "Ndina Muraata Munene", "old": 66, "nzk": 49, "nzk_t": "Ninaye Rafiki", "sdah": 186, "sdah_t": "I've Found a Friend", "tune": "Friend", "cat": "Consecration, Trust & Living"},
  {"nca": 67, "title": "Mwathani mumenyagirire", "old": 67, "nzk": 50, "nzk_t": "Mungu Awe Nanyi Daima", "sdah": 65, "sdah_t": "God Be With You Till We Meet Again", "tune": "Towner", "cat": "Consecration, Trust & Living"},
  {"nca": 68, "title": "Jesu Mukuuri wakwa kuna", "old": 68, "nzk": 51, "nzk_t": "Wimbo wa 51", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 69, "title": "Nihari Mwihoko Wa Goro", "old": 69, "nzk": 162, "nzk_t": "Tumaini Liko", "sdah": 440, "sdah_t": "There Is a Name I Love to Hear", "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 70, "title": "Kwi Na Kiraathimo", "old": 70, "nzk": 47, "nzk_t": "Ni Heri Kifungo", "sdah": 195, "sdah_t": "There Shall Be Showers of Blessing", "tune": "Showers of Blessing", "cat": "Salvation, Atonement & Grace"},
  {"nca": 71, "title": "He Bibilia Njata Ya Gikeno", "old": 71, "nzk": 52, "nzk_t": "Niambie Neno la Uzima", "sdah": 272, "sdah_t": "Give Me the Bible", "tune": "Give Me the Bible", "cat": "Holy Scriptures & Word of God"},
  {"nca": 72, "title": "Ninyendeete Ibuku Ria Ngai", "old": 72, "nzk": 62, "nzk_t": "Neno Lako Taa Yangu", "sdah": 273, "sdah_t": "Lord, I Have Made Thy Word My Choice", "tune": "Holy Bible, Book Divine", "cat": "Holy Scriptures & Word of God"},
  {"nca": 73, "title": "Ninyendeete Kuhuunjia", "old": 73, "nzk": 53, "nzk_t": "Napenda Kuhubiri", "sdah": 457, "sdah_t": "I Love to Tell the Story", "tune": "Hankey", "cat": "Christian Mission & Warfare"},
  {"nca": 74, "title": "We Niukeyuumia Ruuho", "old": 74, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 75, "title": "Ningwenda Kumenya Jesu", "old": 75, "nzk": 54, "nzk_t": "Nataka Nimjue Yesu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 76, "title": "Tuhaandaga Gwakia", "old": 76, "nzk": 55, "nzk_t": "Panda Asubuhi", "sdah": 369, "sdah_t": "Bringing in the Sheaves", "tune": "Harvest", "cat": "Christian Mission & Warfare"},
  {"nca": 77, "title": "Mutihonokiei Aria Mekuura", "old": 77, "nzk": 56, "nzk_t": "Okoa Wanaopotea", "sdah": 367, "sdah_t": "Rescue the Perishing", "tune": "Rescue the Perishing", "cat": "Christian Mission & Warfare"},
  {"nca": 78, "title": "Ndiraririkana Bururi Muthaka", "old": 78, "nzk": 58, "nzk_t": "Nakumbuka Nchi Nzuri", "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 79, "title": "Ndukaarege Wira", "old": 79, "nzk": 57, "nzk_t": "Usikatae Kazi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 80, "title": "Ninyonete Murata Wa Goro", "old": 80, "nzk": 61, "nzk_t": "Nimemwona Rafiki wa Thamani", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 81, "title": "Andu Rutaai Wira", "old": 81, "nzk": 59, "nzk_t": "Fanyeni Kazi Zenu", "sdah": 375, "sdah_t": "Work, for the Night is Coming", "tune": "Diligence", "cat": "Christian Mission & Warfare"},
  {"nca": 82, "title": "Ukaani Tukene Andu A Mwathani", "old": 82, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 83, "title": "Wee Niwe Wandutiire", "old": 83, "nzk": 121, "nzk_t": "Nalitoa Uzima", "sdah": 281, "sdah_t": "I Gave My Life for Thee", "tune": None, "cat": "Worship & Adoration"},
  {"nca": 84, "title": "Riria Nguona Mutharaba", "old": 84, "nzk": 63, "nzk_t": "Nikutanapo na Msalaba", "sdah": 154, "sdah_t": "When I Survey the Wondrous Cross", "tune": "Hamburg", "cat": "Salvation, Atonement & Grace"},
  {"nca": 85, "title": "Ni Utuku Gukiriitwo", "old": 85, "nzk": 66, "nzk_t": "Usiku Mtakatifu", "sdah": 143, "sdah_t": "Silent Night, Holy Night", "tune": "Stille Nacht", "cat": "Children & Youth Songs"},
  {"nca": 86, "title": "Mee Ha Aria Mamenyagirira", "old": 86, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 87, "title": "Jesu Niaretana Mugunda", "old": 87, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 88, "title": "Jesu Mwega Mutheru", "old": 88, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 89, "title": "Ugihanda Na Maithori", "old": 89, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 90, "title": "Turaigua Witano", "old": 90, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 91, "title": "Gwatiai Mataawa Manyu", "old": 91, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 92, "title": "Huuha Coro Wa Injili", "old": 92, "nzk": 64, "nzk_t": "Piga Baragumu ya Injili", "sdah": 614, "sdah_t": "Blow Ye the Trumpet, Blow", "tune": "Lenox", "cat": "Christian Mission & Warfare"},
  {"nca": 93, "title": "Nituthiini Ita Thigari Cia Ngai", "old": 93, "nzk": 65, "nzk_t": "Songeni Mbele Wanajeshi", "sdah": 612, "sdah_t": "Onward, Christian Soldiers", "tune": "St. Gertrude", "cat": "Christian Mission & Warfare"},
  {"nca": 94, "title": "Ngoro Yakwa Arahuka", "old": 94, "nzk": 94, "nzk_t": "Amka, Roho Yangu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 95, "title": "Gitina Kirumu Ni Ciugo Cia Ngai", "old": 95, "nzk": 75, "nzk_t": "Msingi Imara wa Neno", "sdah": 509, "sdah_t": "How Firm a Foundation", "tune": "Foundation", "cat": "Holy Scriptures & Word of God"},
  {"nca": 96, "title": "Arahuka Wee Ngoro", "old": 96, "nzk": 67, "nzk_t": "Amka Roho Uimbe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 97, "title": "Ningwihoka Thakame Io", "old": 97, "nzk": 69, "nzk_t": "Naitumainia Damu Hiyo", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 98, "title": "Ruagirira Ngai", "old": 98, "nzk": 68, "nzk_t": "Mshangilieni Bwana", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 99, "title": "Wiigue Uhooe", "old": 99, "nzk": 71, "nzk_t": "Jinyenyekeze Uombe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 100, "title": "Mbaara Ni Njihu", "old": 100, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 101, "title": "Tugwaka Iguru Ria Ruaro", "old": 101, "nzk": 72, "nzk_t": "Twajenga Juu ya Mwamba", "sdah": 522, "sdah_t": "My Hope Is Built on Nothing Less", "tune": "Solid Rock", "cat": "Worship & Adoration"},
  {"nca": 102, "title": "Undoongorie Mwathi Jesu", "old": 102, "nzk": 73, "nzk_t": "Mwongozi Ee Yehova", "sdah": 545, "sdah_t": "Guide Me, O Thou Great Jehovah", "tune": "Cwm Rhondda", "cat": "Consecration, Trust & Living"},
  {"nca": 103, "title": "Ta Njiira Wee Muraangiri", "old": 103, "nzk": 74, "nzk_t": "Mlinzi, Tuambie", "sdah": 601, "sdah_t": "Watchman, Tell Us of the Night", "tune": "Aberystwyth", "cat": "Second Coming & Christian Hope"},
  {"nca": 104, "title": "Inyui Ni Inyui Ene Uthamaki", "old": 104, "nzk": 76, "nzk_t": "Ninyi Ni Wenye Ufalme", "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 105, "title": "Muraangiri Uruugamite Ruthiingo-ini", "old": 105, "nzk": 77, "nzk_t": "Mlinzi Simama Ukutani", "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 106, "title": "Mwathani Ni Nginya Ri?", "old": 106, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 107, "title": "Mwaki Uria Wakanaga", "old": 107, "nzk": 80, "nzk_t": "Moto Ule Uliowaka", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 108, "title": "Atheru Ukirai", "old": 108, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 109, "title": "Ngwenda Witikio Murumu", "old": 109, "nzk": 79, "nzk_t": "Nataka Imani Imara", "sdah": 533, "sdah_t": "O for a Faith That Will Not Shrink", "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 110, "title": "Gitina Gia Kanitha", "old": 110, "nzk": 195, "nzk_t": "Msingi wa Kanisa", "sdah": 348, "sdah_t": "The Church's One Foundation", "tune": "Aurelia", "cat": "Worship & Adoration"},
  {"nca": 111, "title": "Aria Mendeete Ngai", "old": 111, "nzk": 70, "nzk_t": "Wale Wampendao Mungu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 112, "title": "Mithenya Itaandatu Riu", "old": 112, "nzk": 81, "nzk_t": "Siku Sita Fanya Kazi", "sdah": 388, "sdah_t": "Six Days of Work are Past", "tune": "Sabbath Morn", "cat": "The Sabbath"},
  {"nca": 113, "title": "Muthenya Mutheru", "old": 113, "nzk": 87, "nzk_t": "Siku Takatifu", "sdah": 384, "sdah_t": "Safely Through Another Week", "tune": "Sabbath", "cat": "The Sabbath"},
  {"nca": 114, "title": "Wee Ririkanaga Thabatu", "old": 114, "nzk": 84, "nzk_t": "Kumbuka Sabato Daima", "sdah": 388, "sdah_t": "Don't Forget the Sabbath", "tune": "Don't Forget the Sabbath", "cat": "The Sabbath"},
  {"nca": 115, "title": "Ndi Na Mukuuri Uhaithanagira", "old": 115, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 116, "title": "Muthenya Wa Gikeno", "old": 116, "nzk": 82, "nzk_t": "Siku Kuu ya Mapumziko", "sdah": 382, "sdah_t": "O Day of Rest and Gladness", "tune": "Mendebras", "cat": "The Sabbath"},
  {"nca": 117, "title": "Haria Andu Mahuurukaga", "old": 117, "nzk": 83, "nzk_t": "Mahali pa Pumziko", "sdah": None, "sdah_t": None, "tune": None, "cat": "The Sabbath"},
  {"nca": 118, "title": "Kiumia Kiingi Kigima Nigiathira", "old": 118, "nzk": 85, "nzk_t": "Juma Lingine Limepita", "sdah": None, "sdah_t": None, "tune": None, "cat": "The Sabbath"},
  {"nca": 119, "title": "Muthenya Uyu Wa Thabatu", "old": 119, "nzk": 88, "nzk_t": "Siku Hii ya Sabato", "sdah": None, "sdah_t": None, "tune": None, "cat": "The Sabbath"},
  {"nca": 120, "title": "Thabatu Niyakinya", "old": 120, "nzk": 86, "nzk_t": "Sabato Imefika", "sdah": 385, "sdah_t": "Welcome, Delightful Morn", "tune": "Lischer", "cat": "The Sabbath"},
  {"nca": 121, "title": "Mugaambo Wakwa Ruciini", "old": 121, "nzk": 121, "nzk_t": "Sauti Yangu Asubuhi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Morning & Evening Worship"},
  {"nca": 122, "title": "Mwathani Wakwa Unjikarie", "old": 122, "nzk": 91, "nzk_t": "Kaa Nami", "sdah": 50, "sdah_t": "Abide With Me", "tune": "Eventide", "cat": "Morning & Evening Worship"},
  {"nca": 123, "title": "Riu Nikuraatuka", "old": 123, "nzk": 92, "nzk_t": "Sasa Jioni Yaja", "sdah": None, "sdah_t": None, "tune": None, "cat": "Morning & Evening Worship"},
  {"nca": 124, "title": "Utheri Wa Ngoro", "old": 124, "nzk": 93, "nzk_t": "Nuru ya Moyoni", "sdah": None, "sdah_t": None, "tune": None, "cat": "Morning & Evening Worship"},
  {"nca": 125, "title": "Kuundu Guothe Miguunda-ini", "old": 125, "nzk": 145, "nzk_t": "Kote-kote Mashambani", "sdah": 358, "sdah_t": "Far and Near the Fields Are Teeming", "tune": None, "cat": "Worship & Adoration"},
  {"nca": 126, "title": "Iguai Uhoro Wa Mwathani", "old": 126, "nzk": 95, "nzk_t": "Sikieni Neno la Bwana", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 127, "title": "Nitwagucookeria Indo Ciaku", "old": 127, "nzk": 96, "nzk_t": "Twakurudishia Mali Yako", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 128, "title": "Mwathani Ngai Ningugega O Muno", "old": 128, "nzk": None, "nzk_t": "Bwana Mungu Nashangaa Kabisa", "sdah": 86, "sdah_t": "How Great Thou Art", "tune": "O Store Gud", "cat": "Worship & Adoration"},
  {"nca": 129, "title": "Nguthaambio Meehia Ni Kii?", "old": 129, "nzk": 97, "nzk_t": "Nitaoshwa Dhambi kwa Nini?", "sdah": 336, "sdah_t": "Nothing but the Blood of Jesus", "tune": "Plainfield", "cat": "Salvation, Atonement & Grace"},
  {"nca": 130, "title": "Aria Moorite Mimagacario", "old": 130, "nzk": 100, "nzk_t": "Waliopotea Watafutwe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 131, "title": "Niugwitwo Ni Jesu", "old": 131, "nzk": 101, "nzk_t": "Unaitwa na Yesu", "sdah": 284, "sdah_t": "Softly and Tenderly", "tune": "Thompson", "cat": "Gospel Invitation & Repentance"},
  {"nca": 132, "title": "Mugeni E Muromo-ini", "old": 132, "nzk": 93, "nzk_t": "Mgeni Mlagoni", "sdah": 286, "sdah_t": "Behold a Stranger at the Door", "tune": "Berthold", "cat": "Gospel Invitation & Repentance"},
  {"nca": 133, "title": "Jesu Aratwita Nohooreri", "old": 133, "nzk": 103, "nzk_t": "Yesu Aita kwa Upole", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 134, "title": "Mbuku Ya Ngai Ni Theru", "old": 134, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Holy Scriptures & Word of God"},
  {"nca": 135, "title": "Muriithi Witu Mwega", "old": 135, "nzk": 105, "nzk_t": "Mchungaji Wetu Mwema", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 136, "title": "Jesu Riu Niaretana", "old": 136, "nzk": 107, "nzk_t": "Yesu Sasa Anaita", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 137, "title": "Nituiguite Uhoro", "old": 137, "nzk": 108, "nzk_t": "Tumesikia Habari", "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 138, "title": "Mundu Aigua Nake Niamukirie", "old": 138, "nzk": 109, "nzk_t": "Mwenye Kusikia na Apokee", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 139, "title": "Muraango Nimuhiingure Nguona", "old": 139, "nzk": 110, "nzk_t": "Mlango Umefunguliwa", "sdah": 283, "sdah_t": "The Gate Ajar for Me", "tune": "The Gate Ajar", "cat": "Gospel Invitation & Repentance"},
  {"nca": 140, "title": "Murigiti Munene", "old": 140, "nzk": 111, "nzk_t": "Tabibu Mkuu", "sdah": 438, "sdah_t": "The Great Physician", "tune": "Sympathy", "cat": "Salvation, Atonement & Grace"},
  {"nca": 141, "title": "Ukaani Inyui Eehia", "old": 141, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 142, "title": "Jesu Kristo Niegutwita", "old": 142, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 143, "title": "Wi Munogi Na Muthiini", "old": 143, "nzk": 112, "nzk_t": "Wewe Umechoka Sana?", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 144, "title": "Ukaai Inyui Anogu", "old": 144, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 145, "title": "Nduuriri Niciinamirire", "old": 145, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 146, "title": "Utugi Wa Magegania", "old": 146, "nzk": None, "nzk_t": "Neema Ya Ajabu", "sdah": 108, "sdah_t": "Amazing Grace", "tune": "New Britain", "cat": "Salvation, Atonement & Grace"},
  {"nca": 147, "title": "Ni Nguuga Ugoocwo Ngai", "old": 147, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 148, "title": "Ninjaangite O Kuraya", "old": 148, "nzk": 118, "nzk_t": "Nilipotoka Kabisa", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 149, "title": "Kwi Na Rui Rua Thakame", "old": 149, "nzk": 113, "nzk_t": "Damu Imebubujika", "sdah": 336, "sdah_t": "There Is a Fountain Filled with Blood", "tune": "Cleansing Fountain", "cat": "Salvation, Atonement & Grace"},
  {"nca": 150, "title": "Mwathani Jesu Ngwenda Gutherio", "old": None, "nzk": 114, "nzk_t": "Yesu Mwokozi, Nioshe", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 151, "title": "Mwathani Nii Nimbataire", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 152, "title": "Nimukinyite Hari Jesu", "old": None, "nzk": 117, "nzk_t": "Wamwendea Yesu?", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 153, "title": "Jesu Niaroiga", "old": None, "nzk": 119, "nzk_t": "Yesu Anasema", "sdah": 281, "sdah_t": "Jesus Paid It All", "tune": "All to Christ", "cat": "Salvation, Atonement & Grace"},
  {"nca": 154, "title": "Jesu Njikaria Hau Mutharaba-ini", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 155, "title": "Hari Jesu Ngwiheana", "old": None, "nzk": 122, "nzk_t": "Yote Namtolea Yesu", "sdah": 308, "sdah_t": "I Surrender All", "tune": "Surrender", "cat": "Consecration, Trust & Living"},
  {"nca": 156, "title": "Kwi Na Karima Hakuhi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 157, "title": "Jesu Nioirire Thakame", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 158, "title": "Wi Munogu Na Ugatangika", "old": None, "nzk": 124, "nzk_t": "Umechoka? Je, Umesumbuka?", "sdah": 524, "sdah_t": "Are You Weary, Are You Heavy Hearted?", "tune": "Tell It to Jesus", "cat": "Gospel Invitation & Repentance"},
  {"nca": 159, "title": "Nindaakurutiire Muoyo Wakwa", "old": None, "nzk": 98, "nzk_t": "Nilikupa Wewe", "sdah": 282, "sdah_t": "I Gave My Life for Thee", "tune": "Kenosis", "cat": "Salvation, Atonement & Grace"},
  {"nca": 160, "title": "Warora Mutharaba Wa Jesu", "old": None, "nzk": 125, "nzk_t": "Uniangalie", "sdah": 154, "sdah_t": "When I Survey the Wondrous Cross", "tune": "Hamburg", "cat": "Salvation, Atonement & Grace"},
  {"nca": 161, "title": "Jesu Ngwihokete", "old": None, "nzk": 123, "nzk_t": "Yesu kwa Imani", "sdah": 517, "sdah_t": "'Tis So Sweet to Trust in Jesus", "tune": "Trust in Jesus", "cat": "Consecration, Trust & Living"},
  {"nca": 162, "title": "Thiini Wa Eehia Othe", "old": None, "nzk": 121, "nzk_t": "Kati ya Wenye Dhambi", "sdah": 295, "sdah_t": "Chief of Sinners Though I Be", "tune": "Gethsemane", "cat": "Worship & Adoration"},
  {"nca": 163, "title": "Nimbatairio Niwe", "old": None, "nzk": 126, "nzk_t": "Nina Haja Nawe", "sdah": 483, "sdah_t": "I Need Thee Every Hour", "tune": "Need", "cat": "Prayer & Christian Fellowship"},
  {"nca": 164, "title": "Riria Nguigua Wega", "old": None, "nzk": 127, "nzk_t": "Nionapo Amani Kama Shwari", "sdah": 530, "sdah_t": "It Is Well With My Soul", "tune": "Ville du Havre", "cat": "Consecration, Trust & Living"},
  {"nca": 165, "title": "Numiriire Jesu", "old": None, "nzk": 128, "nzk_t": "Namwandama Bwana", "sdah": 311, "sdah_t": "I Have Decided to Follow Jesus", "tune": "Assam", "cat": "Consecration, Trust & Living"},
  {"nca": 166, "title": "Ningenagio Ni Kwihoka", "old": None, "nzk": 129, "nzk_t": "Kumtegemea Mwokozi", "sdah": 517, "sdah_t": "'Tis So Sweet to Trust in Jesus", "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 167, "title": "Meehia Maku Mangikoruo", "old": None, "nzk": 167, "nzk_t": "Yesu Bwana Mwokozi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 168, "title": "Ti Itheru Twi Muraata", "old": None, "nzk": 130, "nzk_t": "Yesu Kwetu ni Rafiki", "sdah": 499, "sdah_t": "What a Friend We Have in Jesus", "tune": "Converse", "cat": "Prayer & Christian Fellowship"},
  {"nca": 169, "title": "Mabataro-ini Ma Ruuciu", "old": None, "nzk": 131, "nzk_t": "Hapo Yesu Atakapoita", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 170, "title": "Mwathani Ni Muriithi", "old": None, "nzk": 132, "nzk_t": "Bwana ni Mchunga", "sdah": 552, "sdah_t": "The Lord's My Shepherd", "tune": "Crimond", "cat": "Consecration, Trust & Living"},
  {"nca": 171, "title": "Tuura Wi Mutheru", "old": None, "nzk": 134, "nzk_t": "Tafuta Daima Utakatifu", "sdah": 531, "sdah_t": "Take Time to Be Holy", "tune": "Holiness", "cat": "Consecration, Trust & Living"},
  {"nca": 172, "title": "Igua Wega Ciugo Cia Jesu", "old": None, "nzk": 172, "nzk_t": "Mfalme Wetu Atuita", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 173, "title": "Jesu Mukuuri Niwe Njira", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 174, "title": "O Guothe Jesu E Ho", "old": None, "nzk": 133, "nzk_t": "Po Pote na Yesu", "sdah": 508, "sdah_t": "Anywhere with Jesus", "tune": "Security", "cat": "Worship & Adoration"},
  {"nca": 175, "title": "Maikarite Thi Utuku", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 176, "title": "Wendo Waku We Mukuuri", "old": None, "nzk": 37, "nzk_t": "Pendo Lako Ee Mwokozi", "sdah": 343, "sdah_t": "I Will Sing of Jesus' Love", "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 177, "title": "Jesu Ni Muriithi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 178, "title": "Hindi Njega Ya Mahooya", "old": None, "nzk": 135, "nzk_t": "Saa Heri ya Maombi", "sdah": 478, "sdah_t": "Sweet Hour of Prayer", "tune": "Sweet Hour", "cat": "Prayer & Christian Fellowship"},
  {"nca": 179, "title": "Ihinda Ria Kuhooya", "old": None, "nzk": 137, "nzk_t": "Saa Heri ya Sala", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 180, "title": "Nindiikurumagirira", "old": None, "nzk": 138, "nzk_t": "Nitakuandama Kote", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 181, "title": "Nyinirai Oro Riingi", "old": None, "nzk": 139, "nzk_t": "Uliniimbie Tena", "sdah": 286, "sdah_t": "Wonderful Words of Life", "tune": "Words of Life", "cat": "Holy Scriptures & Word of God"},
  {"nca": 182, "title": "Njoya Uguo Ndarii Jesu", "old": None, "nzk": 140, "nzk_t": "Nitwae Hivi Nilivyo", "sdah": 313, "sdah_t": "Just As I Am", "tune": "Woodworth", "cat": "Consecration, Trust & Living"},
  {"nca": 183, "title": "Ninguigua Mugambo", "old": None, "nzk": 142, "nzk_t": "Nasikia Mwito", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 184, "title": "Ndi Waku Jesu", "old": None, "nzk": 144, "nzk_t": "Ni Wako Bwana", "sdah": 306, "sdah_t": "I Am Thine, O Lord", "tune": "I Am Thine", "cat": "Consecration, Trust & Living"},
  {"nca": 185, "title": "Thi Ino Ni Inogete", "old": None, "nzk": 145, "nzk_t": "Ulimwengu Siutaki", "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 186, "title": "Njoya Njoya Mwathani", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 187, "title": "Thakame Ya Jesu", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 188, "title": "Nguucia Hakuhi Nawe Baba", "old": None, "nzk": 148, "nzk_t": "Univute Karibu", "sdah": 473, "sdah_t": "Nearer, My God, to Thee", "tune": "Bethany", "cat": "Prayer & Christian Fellowship"},
  {"nca": 189, "title": "Haha Mutharaba-ini", "old": None, "nzk": 141, "nzk_t": "Chini ya Msalaba", "sdah": 163, "sdah_t": "At the Cross", "tune": "Hudson", "cat": "Salvation, Atonement & Grace"},
  {"nca": 190, "title": "Mwathani Riu Ndigiite Maundu", "old": None, "nzk": 190, "nzk_t": "Raha Yangu Yote, Bwana", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 191, "title": "Ningwenda Nduike Mwana Waku", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 192, "title": "Thamaka Thiini Wakwa", "old": None, "nzk": 147, "nzk_t": "Tawala Ndani Yangu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 193, "title": "Kwenda Gwaku Ngai", "old": None, "nzk": 193, "nzk_t": "Sauti ya Mchungaji", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 194, "title": "Nguuka Mutharaba-ini", "old": None, "nzk": 115, "nzk_t": "Naendea Msalaba", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 195, "title": "Baba Ndiri Na Uteithio Ungi", "old": None, "nzk": 143, "nzk_t": "Baba Sina Msaada", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 196, "title": "Ciugo Njuru Wee Ungaanie", "old": None, "nzk": 150, "nzk_t": "Hasha Maneno Mabaya", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 197, "title": "Niandoongoragia Mwathani", "old": None, "nzk": 151, "nzk_t": "Huniongoza Mwokozi", "sdah": 537, "sdah_t": "He Leadeth Me", "tune": "Aughton", "cat": "Consecration, Trust & Living"},
  {"nca": 198, "title": "Hakuhi Nawe Ngai", "old": None, "nzk": 152, "nzk_t": "Karibu na Wewe", "sdah": 473, "sdah_t": "Nearer, My God, to Thee", "tune": "Bethany", "cat": "Consecration, Trust & Living"},
  {"nca": 199, "title": "Riciiria No Rimwe", "old": None, "nzk": 153, "nzk_t": "Fikira Moja tu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 200, "title": "Njagiriiruo Ngoruo Nake", "old": None, "nzk": 154, "nzk_t": "Yanipasa Kuwa Naye", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 201, "title": "Kuria Daudi Aaciariiruo", "old": None, "nzk": None, "nzk_t": "Huko Bethlehemu", "sdah": 149, "sdah_t": "Once in Royal David's City", "tune": "Irby", "cat": "Children & Youth Songs"},
  {"nca": 202, "title": "Ngucaria Jesu O Riu", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 203, "title": "Mooko-ini Ma Jesu", "old": None, "nzk": None, "nzk_t": "Mikononi Mwa Yesu", "sdah": 470, "sdah_t": "Safe in the Arms of Jesus", "tune": "Safe in the Arms", "cat": "Worship & Adoration"},
  {"nca": 204, "title": "Kuria Guothe Angienda Thii", "old": None, "nzk": 133, "nzk_t": "Po Pote na Yesu", "sdah": 508, "sdah_t": "Anywhere with Jesus", "tune": "Security", "cat": "Consecration, Trust & Living"},
  {"nca": 205, "title": "Muhonokia E Hakuhi", "old": None, "nzk": 157, "nzk_t": "Mfalme yu Mlangoni", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 206, "title": "Hatigairie aigana Atia", "old": None, "nzk": 158, "nzk_t": "U mwendo Gani Nyumbani?", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 207, "title": "Ni Uhoro Mwega Ma", "old": None, "nzk": 159, "nzk_t": "Anakuja Upesi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 208, "title": "Aria Atheru Wihuugei", "old": None, "nzk": 160, "nzk_t": "Watakatifu Kesheni", "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 209, "title": "Huuhai Coro Mugaambie Muno", "old": None, "nzk": 161, "nzk_t": "Piga Panda", "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 210, "title": "Muthenya Wa Gucooka Kwa Jesu", "old": None, "nzk": 164, "nzk_t": "Unakaribia Wakati", "sdah": 213, "sdah_t": "Lift Up the Trumpet", "tune": "Silver Trumpet", "cat": "Second Coming & Christian Hope"},
  {"nca": 211, "title": "Kiiriro Kiega Kia Eetikia", "old": None, "nzk": 165, "nzk_t": "Ahadi Tamu", "sdah": 214, "sdah_t": "We Have This Hope", "tune": "We Have This Hope", "cat": "Second Coming & Christian Hope"},
  {"nca": 212, "title": "Tutiui Hindi Iria Angiuka", "old": None, "nzk": 174, "nzk_t": "Sijui Atakapokuja", "sdah": 604, "sdah_t": "We Know Not the Hour", "tune": "We Know Not the Hour", "cat": "Second Coming & Christian Hope"},
  {"nca": 213, "title": "Gikeno Guuku Thi Guothe", "old": None, "nzk": 166, "nzk_t": "Furaha kwa Ulimwengu", "sdah": 125, "sdah_t": "Joy to the World", "tune": "Antioch", "cat": "Praise & Thanksgiving"},
  {"nca": 214, "title": "Thikiriria Makiina", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 215, "title": "Onei Agiuka Riera-ini", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 216, "title": "Angigooka Riri Ruoro Rutemaga", "old": None, "nzk": 163, "nzk_t": "Pengine Ni Saa", "sdah": 218, "sdah_t": "When He Cometh", "tune": "Jewels", "cat": "Second Coming & Christian Hope"},
  {"nca": 217, "title": "Nieguuka O Riingi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 218, "title": "Kai Jesu Ni Mwega", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 219, "title": "Jesu Muhonokia", "old": None, "nzk": 167, "nzk_t": "Yesu Bwana Mwokozi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 220, "title": "Niwokire Tondu Wakunyeenda", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 221, "title": "Coro Wa Ngai Ukahuuhwo", "old": None, "nzk": 168, "nzk_t": "Tarumbeta ya Mwana", "sdah": 216, "sdah_t": "When the Roll is Called Up Yonder", "tune": "Roll Call", "cat": "Second Coming & Christian Hope"},
  {"nca": 222, "title": "Ndingicaria Utoonga", "old": None, "nzk": 170, "nzk_t": "Siitafuti Mali", "sdah": 440, "sdah_t": "Is My Name Written There?", "tune": "Is My Name Written There", "cat": "Heaven & Life Everlasting"},
  {"nca": 223, "title": "Muthamaki Niatwitite", "old": None, "nzk": 172, "nzk_t": "Mfalme Wetu Atuita", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 224, "title": "Ciira Niwambiriirio Iguru", "old": None, "nzk": 171, "nzk_t": "Imeanzishwa Hukumu", "sdah": 416, "sdah_t": "The Judgment Has Set", "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 225, "title": "Tutiui Thaa", "old": None, "nzk": 173, "nzk_t": "Hatujui Saa", "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 226, "title": "Nguuka Ndige Nduma Na Kieha", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 227, "title": "Riria Jesu Agacookereria", "old": None, "nzk": 169, "nzk_t": "Hapo Yesu Atakapoita", "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 228, "title": "Twi Na Ciikaro Matu-ini", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 229, "title": "Nitukonana Na Jesu", "old": None, "nzk": 175, "nzk_t": "Nitaonana na Yesu", "sdah": 432, "sdah_t": "Shall We Gather at the River?", "tune": "Hanson Place", "cat": "Heaven & Life Everlasting"},
  {"nca": 230, "title": "Tugaacemania Ruui-ini", "old": None, "nzk": 176, "nzk_t": "Ati twonane Mtoni?", "sdah": 432, "sdah_t": "Shall We Gather at the River?", "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 231, "title": "Wira Wakwa Wathira", "old": None, "nzk": 177, "nzk_t": "Kazi Yangu Ikiisha", "sdah": 430, "sdah_t": "When My Life Work Is Ended", "tune": "I Shall Know Him", "cat": "Heaven & Life Everlasting"},
  {"nca": 232, "title": "Uka Kwi Jesu Ndukaarege", "old": None, "nzk": 99, "nzk_t": "Uje kwa Yesu Usikatae", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 233, "title": "Murimo Uria Wa Jordani", "old": None, "nzk": 178, "nzk_t": "Ukingoni Mwa Yordani", "sdah": 620, "sdah_t": "On Jordan's Stormy Banks", "tune": "Varina", "cat": "Heaven & Life Everlasting"},
  {"nca": 234, "title": "Hindi Iria Wira Ugaathira", "old": None, "nzk": 179, "nzk_t": "Wavunaji Watafurahi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 235, "title": "NiKuri Bururi Mwega Ma", "old": None, "nzk": 180, "nzk_t": "Pana Mahali Pazuri Mno", "sdah": 428, "sdah_t": "Sweet By and By", "tune": "Sweet By and By", "cat": "Heaven & Life Everlasting"},
  {"nca": 236, "title": "Ngatuura Ruui-ini", "old": None, "nzk": 181, "nzk_t": "Mahali pa Maji", "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 237, "title": "Kuu Gutitukaga", "old": None, "nzk": 182, "nzk_t": "Mchana Hauishi", "sdah": 427, "sdah_t": "No Night There", "tune": "No Night There", "cat": "Heaven & Life Everlasting"},
  {"nca": 238, "title": "Magerio Maathira Ndiikie Wira", "old": None, "nzk": 183, "nzk_t": "Furaha na Raha", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 239, "title": "Twaragia Uhoro Mwega", "old": None, "nzk": 184, "nzk_t": "Vitu Vyote ni Sawa", "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 240, "title": "Ningeekira Thuumbi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Morning & Evening Worship"},
  {"nca": 241, "title": "Mucii Wi Na Wendani", "old": None, "nzk": 184, "nzk_t": "Nyumbani Mna Furaha", "sdah": 652, "sdah_t": "Love at Home", "tune": "Love at Home", "cat": "Prayer & Christian Fellowship"},
  {"nca": 242, "title": "Ngai Wi Wendo Mukinyaniru", "old": None, "nzk": 185, "nzk_t": "Mungu U Mapenzi", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 243, "title": "Riria Tuonana Na Araata", "old": None, "nzk": 186, "nzk_t": "Tuonanapo na Rafiki", "sdah": 350, "sdah_t": "Blest Be the Tie That Binds", "tune": "Dennis", "cat": "Morning & Evening Worship"},
  {"nca": 244, "title": "Gukoma Hamwe Na Jesu", "old": None, "nzk": 187, "nzk_t": "Kufariki Naye Yesu", "sdah": 305, "sdah_t": "Asleep in Jesus", "tune": "Rest", "cat": "Worship & Adoration"},
  {"nca": 245, "title": "Nindionerire Githima", "old": None, "nzk": 188, "nzk_t": "Wimbi la Damu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 246, "title": "Huuruka Wega", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 247, "title": "Tubatithie Na Hinya Wa Iguru", "old": None, "nzk": 189, "nzk_t": "Mimina Upya", "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 248, "title": "Mugate Wa Muoyo", "old": None, "nzk": 191, "nzk_t": "Mkate wa Mbingu", "sdah": 274, "sdah_t": "Break Thou the Bread of Life", "tune": "Bread of Life", "cat": "Holy Scriptures & Word of God"},
  {"nca": 249, "title": "Twatua Kuria Giathi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 250, "title": "Ihiga Ria Tene Ma", "old": None, "nzk": 192, "nzk_t": "Mwamba Wenye Imara", "sdah": 300, "sdah_t": "Rock of Ages, Cleft for Me", "tune": "Toplady", "cat": "Salvation, Atonement & Grace"},
  {"nca": 251, "title": "Ni Mugaambo Wa Muriithi", "old": None, "nzk": 193, "nzk_t": "Sauti ya Mchungaji", "sdah": 359, "sdah_t": "Hark! The Voice of Jesus Calling", "tune": "Galilee", "cat": "Christian Mission & Warfare"},
  {"nca": 252, "title": "Twahooya Ngai Umuoe", "old": None, "nzk": 194, "nzk_t": "Twaomba Bwana", "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 253, "title": "Magaatura O Na Jesu Kuo", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Heaven & Life Everlasting"},
  {"nca": 254, "title": "Ndugetikirie Meehia Makuhoote", "old": None, "nzk": None, "nzk_t": "Ushinde Majaribu", "sdah": 608, "sdah_t": "Yield Not to Temptation", "tune": "Yield Not", "cat": "Christian Mission & Warfare"},
  {"nca": 255, "title": "Mwathani Niariukite", "old": None, "nzk": None, "nzk_t": "Bwana Amefufuka", "sdah": 166, "sdah_t": "Christ the Lord Is Risen Today", "tune": "Easter Hymn", "cat": "Worship & Adoration"},
  {"nca": 256, "title": "Nindithaambire Mooko", "old": None, "nzk": 198, "nzk_t": "Nilinawa Mikono", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 257, "title": "Iguai Mugaambo Mbeeca Ikigaamba", "old": None, "nzk": 202, "nzk_t": "Sikia Mlio", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 258, "title": "Wendo Niguo Gikeno", "old": None, "nzk": 199, "nzk_t": "Upendo ni Furaha", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 259, "title": "Jesu Niwe Munyeendi", "old": None, "nzk": 197, "nzk_t": "Anipenda ni Kweli", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 260, "title": "Riria Jesu Agacooka", "old": None, "nzk": 196, "nzk_t": "Kitambo Bwana Yuaja", "sdah": 218, "sdah_t": "When He Cometh", "tune": "Jewels", "cat": "Second Coming & Christian Hope"},
  {"nca": 261, "title": "Gwitu Twaikara Na Jesu", "old": None, "nzk": 204, "nzk_t": "Kuwa na Yesu Nyumbani", "sdah": None, "sdah_t": None, "tune": None, "cat": "Benedictions & Doxologies"},
  {"nca": 262, "title": "Ngai Niendeete Tunyoni", "old": None, "nzk": 201, "nzk_t": "Mungu Huona Vindege", "sdah": 190, "sdah_t": "God Sees the Little Sparrow Fall", "tune": "Sparrow", "cat": "Worship & Adoration"},
  {"nca": 263, "title": "Ninjiguaga Gikeno Kiingi", "old": None, "nzk": 200, "nzk_t": "Baba Yetu Aliye Mbinguni", "sdah": None, "sdah_t": None, "tune": None, "cat": "Praise & Thanksgiving"},
  {"nca": 264, "title": "Ni Guuka Eguuka", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Second Coming & Christian Hope"},
  {"nca": 265, "title": "Ningeekira Thuumbi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 266, "title": "Kaana Ka Mariamu", "old": None, "nzk": None, "nzk_t": "Kitandani Mwa Ng'ombe", "sdah": 124, "sdah_t": "Away in a Manger", "tune": "Cradle Song", "cat": "Children & Youth Songs"},
  {"nca": 267, "title": "Njata Ngeengi Cia Na Kuu Matu-ini", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 268, "title": "Tuoko Ni Twa Wira", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 269, "title": "Jesu Nienda Twaana Tuniini Ta Nii", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Children & Youth Songs"},
  {"nca": 270, "title": "Mbuku Ikuuga", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Holy Scriptures & Word of God"},
  {"nca": 271, "title": "Jesu Nienda Twana Tuothe", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Children & Youth Songs"},
  {"nca": 272, "title": "Zakayo", "old": None, "nzk": None, "nzk_t": "Zakayo Mbilikimo", "sdah": None, "sdah_t": "Zacchaeus Was a Wee Little Man", "tune": "Zacchaeus", "cat": "Children & Youth Songs"},
  {"nca": 273, "title": "Ninyeenda Muno Thiage Sabbath School", "old": None, "nzk": None, "nzk_t": "Napenda Kwenda Sabbath School", "sdah": None, "sdah_t": "I Love to Go to Sabbath School", "tune": "Sabbath School", "cat": "Children & Youth Songs"},
  {"nca": 274, "title": "Ndi Na Bibilia Igiri", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Holy Scriptures & Word of God"},
  {"nca": 275, "title": "Miithi Itandatu Ni Wira", "old": None, "nzk": 203, "nzk_t": "Siku Sita Fanya Kazi", "sdah": None, "sdah_t": None, "tune": None, "cat": "The Sabbath"},
  {"nca": 276, "title": "Jesu Muriithi Wakwa", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 277, "title": "Ngwenda Ngoruo Ndihaariirie", "old": None, "nzk": 214, "nzk_t": "Nataka Niwe Tayari", "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 278, "title": "Jesu Mwendwa Muhonokia", "old": None, "nzk": 218, "nzk_t": "Yesu Mwokozi Mpendwa", "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 279, "title": "Mwathani Nyita Riu", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Prayer & Christian Fellowship"},
  {"nca": 280, "title": "Kristo Nowe", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 281, "title": "Witikio Wakwa Ngugaira Aria Angi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Christian Mission & Warfare"},
  {"nca": 282, "title": "Ndi Njira-ini Ngithii Matu-ini", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 283, "title": "Twagucookeria Ngaatho", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Benedictions & Doxologies"},
  {"nca": 284, "title": "Ngoma Airagia Ngoro Yaakwa", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Salvation, Atonement & Grace"},
  {"nca": 285, "title": "Ngai Akuragia Nyeni Gwiitu Muguunda", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 286, "title": "Mukuunga Mbura Ni Wa-u?", "old": None, "nzk": 208, "nzk_t": "Mungu Afanya Upinde", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 287, "title": "Nuu Ungiumba Ihua?", "old": None, "nzk": 207, "nzk_t": "Nani Ayafanya Maua", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 288, "title": "Tubeca Tuutu Muhiuhe", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 289, "title": "Andu A Thi Mabataire Kuona Mwathani", "old": None, "nzk": 215, "nzk_t": "Ulimwengu Wataka", "sdah": None, "sdah_t": None, "tune": None, "cat": "The Sabbath"},
  {"nca": 290, "title": "Guuku Ni Kuri Waganu Muingi", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 291, "title": "Roho Wa Ngai Witu", "old": None, "nzk": 210, "nzk_t": "Roho Wa Mungu Wangu", "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 292, "title": "Twaana Tuothe Tumenye", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Children & Youth Songs"},
  {"nca": 293, "title": "Jesu Niendaga Nduike", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 294, "title": "Jesu Ngukuuma Thuutha", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Consecration, Trust & Living"},
  {"nca": 295, "title": "Nyina Nyau Oigaga", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Gospel Invitation & Repentance"},
  {"nca": 296, "title": "Twi Gakundi Ga Twaana", "old": None, "nzk": 209, "nzk_t": "Napenda Sana Kufika", "sdah": None, "sdah_t": None, "tune": None, "cat": "Children & Youth Songs"},
  {"nca": 297, "title": "Tigwo Uhoro", "old": None, "nzk": 220, "nzk_t": "Kwa Heri", "sdah": None, "sdah_t": None, "tune": None, "cat": "Benedictions & Doxologies"},
  {"nca": 298, "title": "Tuitho Tutu Thuuragai", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"},
  {"nca": 299, "title": "Muriithi Mwega W Ngondu", "old": None, "nzk": None, "nzk_t": None, "sdah": None, "sdah_t": None, "tune": None, "cat": "Worship & Adoration"}
]

with open("public/data/nca_master_index.json", "w", encoding="utf-8") as f:
    json.dump(records, f, indent=2, ensure_ascii=False)

print(f"Successfully generated public/data/nca_master_index.json with {len(records)} hymns.")
